export default {
    Rithou: ["Vasant", "Grisma", "Varsha", "Sarada", "Hemant", "Sisira"],
    Varsha: ["Sobakr", "Krothi"],
    Paksha: ["krisna", "Shukla"],
    Tithi: ["Pradam", "Dvithi", "Trithi", "Chatur", "Pancha", "Sashti", "Saptha", "Astami", "Navami", "Dasami", "Ekadas", "Dvadas", "Triyod", "Chadas", "Pourni", "Ammava", "Suniya"],
    Nakshtra: [
        "Aswini",
        "Barani",
        "Kritik",
        "Rohini",
        "Mrigas",
        "Aarudh",
        "Punarv",
        "Pushya",
        "Ayilya",
        "Magha",
        "Pooram",
        "Uthram",
        "Hastha",
        "Chitra",
        "Swaati",
        "Visaka",
        "Anurad",
        "Jyesta",
        "Moolam",
        "Poorad",
        "Uthrad",
        "Sravan",
        "Avitam",
        "Sadyam",
        "Poorat",
        "Utrata",
        "Revati",
    ],
    TMonth: ["Chitra", "Vaikas", "Aani", "Aadi", "Aavani", "Purata", "Ippasi", "Karthi", "Margay", "Thai", "Maasi", "Pankun"]
};
